GET http://localhost:5001/api/notes
###
GET http://localhost:5001/api/notes/6447b5f882afc015ca5994ca
###

POST http://localhost:5001/api/notes
Content-Type: application/json

{
  "title": "Third notes ",
  "text": "This is my third note \nNext line"
}

###

PUT http://localhost:5001/api/notes/6447b5f882afc015ca5994ca
Content-Type: application/json

{
  "title": "My very second note",
  "text": "This is my very second note"
}

###
DELETE http://localhost:5001/api/notes/6447c5b3a408d787a740d83a
